CREATE TABLE USERACCOUNT(
    ID INT(10) NOT NULL AUTO_INCREMENT,
    USERNAME CHAR(25) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD CHAR(60) NOT NULL,
    PRIMARY KEY (ID)
);
INSERT INTO USERACCOUNT(USERNAME,EMAIL,PASSWORD)
    VALUES ("gustavo","gustavo@dominio.com","123");

SELECT USERNAME FROM USERACCOUNT USR WHERE USR.USERNAME = "LegutW";

CREATE TABLE USERACCOUNT (id INT NOT NULL PRIMARY KEY, 
name VARCHAR(20),
USERNAME VARCHAR(25),
EMAIL CHAR(1), 
PASSWORD VARCHAR(60) not null);